### ISSUE TITLE
Refactor to Class API

### ISSUE THREAD

**Issue by AGausmann** [OpenRedstoneEngineers/OREUtilsV2#23]
Currently as our code stands, it is not fit for updating to CraftBukkit 1.8. The ["new" edition] (http://dev.bukkit.org/bukkit-plugins/pploader/) of the Python plugin loader has removed the decorator API that we use, so we need to change our code to use the Class API. 
EDIT: I've made a [dedicated branch](https://github.com/OpenRedstoneEngineers/OREUtilsV2/tree/classAPI) for anyone who wants to help with the port to the class API.

**Comment by jomo** [comment]
I don't play on ORE a lot but my IGN is jomo as well. The original python loader has been broken for quite a while, but are there additional (python loader-)breaking changes in 1.8?
If so, that fork is probably broken as well because it hasn't been updated in a while.

**Comment by agausmann** [comment]
Closed due to irrelevance.
